import type { Metadata } from "next";
import "./globals.css";
import { Mulish } from "next/font/google";
import { Header } from "@/components/global/Header/Header";
import { Footer } from "@/components/global/Footer/Footer";
import { ChatButton } from "@/components/elements/ChatButton";
import { SpinButton } from "@/components/elements/WheelButton";

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${mulish.variable} font-mulish antialiased`}>
        <Header />
        {children}
        <SpinButton />
        <ChatButton />
        <Footer />
      </body>
    </html>
  );
}
