import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/global/Header/Header";
import { Footer } from "@/components/global/Footer/Footer";
import { ChatButton } from "@/components/elements/ChatButton";
import { SpinButton } from "@/components/elements/WheelButton";
import MobileNavbar from "@/components/global/Header/MobileNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Header /> */}
        <MobileNavbar />
        {children}
        <SpinButton />
        <ChatButton />
        <Footer />
      </body>
    </html>
  );
}
